// GENERATED by scripts/compare/compare-data.mjs - do not hand-edit.
// Per mock file: ordered compare entries (n=pair name, l=tab label, b=before, a=after).
window.COMPARE_DATA = {
 "onboarding-a41.html": [
  {
   "n": "acquire-OnBoarding",
   "l": "Main",
   "b": "compare/before/acquire-OnBoarding.png",
   "a": "compare/after/acquire-OnBoarding.png"
  },
  {
   "n": "acquire-OnBoarding--slide-2",
   "l": "Slide 2",
   "b": "compare/before/acquire-OnBoarding--slide-2.png",
   "a": "compare/after/acquire-OnBoarding--slide-2.png"
  },
  {
   "n": "acquire-OnBoarding--slide-3",
   "l": "Slide 3",
   "b": "compare/before/acquire-OnBoarding--slide-3.png",
   "a": "compare/after/acquire-OnBoarding--slide-3.png"
  }
 ],
 "login-a42.html": [
  {
   "n": "acquire-Login",
   "l": "Main",
   "b": "compare/before/acquire-Login.png",
   "a": "compare/after/acquire-Login.png"
  },
  {
   "n": "acquire-Login--filled-busy",
   "l": "Filled busy",
   "b": "compare/before/acquire-Login--filled-busy.png",
   "a": "compare/after/acquire-Login--filled-busy.png"
  },
  {
   "n": "acquire-Login--invalid",
   "l": "Invalid",
   "b": "compare/before/acquire-Login--invalid.png",
   "a": "compare/after/acquire-Login--invalid.png"
  },
  {
   "n": "acquire-Login--login-mode",
   "l": "Login mode",
   "b": "compare/before/acquire-Login--login-mode.png",
   "a": "compare/after/acquire-Login--login-mode.png"
  }
 ],
 "verifycode-a43.html": [
  {
   "n": "acquire-VerifyCode",
   "l": "Main",
   "b": "compare/before/acquire-VerifyCode.png",
   "a": "compare/after/acquire-VerifyCode.png"
  },
  {
   "n": "acquire-VerifyCode--counting",
   "l": "Counting",
   "b": "compare/before/acquire-VerifyCode--counting.png",
   "a": "compare/after/acquire-VerifyCode--counting.png"
  },
  {
   "n": "acquire-VerifyCode--wrong-otp",
   "l": "Wrong otp",
   "b": "compare/before/acquire-VerifyCode--wrong-otp.png",
   "a": "compare/after/acquire-VerifyCode--wrong-otp.png"
  },
  {
   "n": "acquire-VerifyCode--verifying",
   "l": "Verifying",
   "b": "compare/before/acquire-VerifyCode--verifying.png",
   "a": "compare/after/acquire-VerifyCode--verifying.png"
  }
 ],
 "splash-a44.html": [
  {
   "n": "acquire-Splash",
   "l": "Main",
   "b": null,
   "a": "compare/after/acquire-Splash.png"
  }
 ],
 "activate-identity-forms.html": [
  {
   "n": "activate-BioDetails",
   "l": "Bio details",
   "b": "compare/before/activate-BioDetails.png",
   "a": "compare/after/activate-BioDetails.png"
  },
  {
   "n": "activate-EducationDetails",
   "l": "Education",
   "b": "compare/before/activate-EducationDetails.png",
   "a": "compare/after/activate-EducationDetails.png"
  },
  {
   "n": "activate-EmergencyContact",
   "l": "Emergency contact",
   "b": "compare/before/activate-EmergencyContact.png",
   "a": "compare/after/activate-EmergencyContact.png"
  }
 ],
 "activate-location-pin.html": [
  {
   "n": "activate-SetHomeLocationPin",
   "l": "Main",
   "b": null,
   "a": "compare/after/activate-SetHomeLocationPin.png"
  },
  {
   "n": "activate-SetHomeLocationPin--picker",
   "l": "Picker",
   "b": null,
   "a": "compare/after/activate-SetHomeLocationPin--picker.png"
  },
  {
   "n": "activate-SetHomeLocationPin--autofilled",
   "l": "Autofilled",
   "b": null,
   "a": "compare/after/activate-SetHomeLocationPin--autofilled.png"
  }
 ],
 "activate-service-preference.html": [
  {
   "n": "activate-ServicePreferenceStep1",
   "l": "Step 1 · teach",
   "b": "compare/before/activate-ServicePreferenceStep1.png",
   "a": "compare/after/activate-ServicePreferenceStep1.png"
  },
  {
   "n": "activate-ServicePreferenceStep2",
   "l": "Step 2 · where",
   "b": "compare/before/activate-ServicePreferenceStep2.png",
   "a": "compare/after/activate-ServicePreferenceStep2.png"
  },
  {
   "n": "activate-AvailabilitySlots",
   "l": "Step 3 · when",
   "b": "compare/before/activate-AvailabilitySlots.png",
   "a": "compare/after/activate-AvailabilitySlots.png"
  },
  {
   "n": "activate-ServicePreferenceStep1--first-run",
   "l": "First run",
   "b": "compare/before/activate-ServicePreferenceStep1--first-run.png",
   "a": "compare/after/activate-ServicePreferenceStep1--first-run.png"
  }
 ],
 "activate-teaching-area.html": [
  {
   "n": "activate-SetTeachingArea",
   "l": "Main",
   "b": null,
   "a": "compare/after/activate-SetTeachingArea.png"
  },
  {
   "n": "activate-SetTeachingArea--set-area",
   "l": "Set area",
   "b": null,
   "a": "compare/after/activate-SetTeachingArea--set-area.png"
  },
  {
   "n": "activate-SetTeachingArea--online",
   "l": "Online",
   "b": null,
   "a": "compare/after/activate-SetTeachingArea--online.png"
  }
 ],
 "activate-uploads.html": [
  {
   "n": "activate-VerificationDocumentsUpload",
   "l": "Documents",
   "b": "compare/before/activate-VerificationDocumentsUpload.png",
   "a": "compare/after/activate-VerificationDocumentsUpload.png"
  },
  {
   "n": "activate-IntroVideoUpload",
   "l": "Intro video",
   "b": "compare/before/activate-IntroVideoUpload.png",
   "a": "compare/after/activate-IntroVideoUpload.png"
  },
  {
   "n": "activate-TutorVerificationProcess--under-review",
   "l": "Under review",
   "b": "compare/before/activate-TutorVerificationProcess--under-review.png",
   "a": "compare/after/activate-TutorVerificationProcess--under-review.png"
  }
 ],
 "activate-application-submitted.html": [
  {
   "n": "activate-VerificationSubmittedSuccess",
   "l": "Submitted",
   "b": "compare/before/activate-VerificationSubmittedSuccess.png",
   "a": "compare/after/activate-VerificationSubmittedSuccess.png"
  }
 ],
 "activate-unverify-gate.html": [
  {
   "n": "activate-UnverifyScreen",
   "l": "Gate",
   "b": "compare/before/activate-UnverifyScreen.png",
   "a": "compare/after/activate-UnverifyScreen.png"
  },
  {
   "n": "activate-TutorVerificationProcess",
   "l": "Checklist",
   "b": "compare/before/activate-TutorVerificationProcess.png",
   "a": "compare/after/activate-TutorVerificationProcess.png"
  },
  {
   "n": "activate-TutorVerificationProcess--complete",
   "l": "Complete",
   "b": "compare/before/activate-TutorVerificationProcess--complete.png",
   "a": "compare/after/activate-TutorVerificationProcess--complete.png"
  }
 ],
 "requests-feed-r1.html": [
  {
   "n": "participate-TutorRequests",
   "l": "Main",
   "b": "compare/before/participate-TutorRequests.png",
   "a": "compare/after/participate-TutorRequests.png"
  },
  {
   "n": "participate-TutorRequests--scrolled",
   "l": "Scrolled",
   "b": "compare/before/participate-TutorRequests--scrolled.png",
   "a": "compare/after/participate-TutorRequests--scrolled.png"
  },
  {
   "n": "participate-TutorRequests--new-chip",
   "l": "New chip",
   "b": "compare/before/participate-TutorRequests--new-chip.png",
   "a": "compare/after/participate-TutorRequests--new-chip.png"
  }
 ],
 "wave1-apply-detail.html": [
  {
   "n": "participate-RequestDetails",
   "l": "Detail",
   "b": "compare/before/participate-RequestDetails.png",
   "a": "compare/after/participate-RequestDetails.png"
  },
  {
   "n": "participate-RequestDetailById",
   "l": "vs live ById",
   "b": "compare/before/participate-RequestDetailById.png",
   "a": "compare/after/participate-RequestDetailById.png"
  },
  {
   "n": "participate-RecommendedRequestDetail",
   "l": "vs live Recommended",
   "b": "compare/before/participate-RecommendedRequestDetail.png",
   "a": "compare/after/participate-RecommendedRequestDetail.png"
  },
  {
   "n": "participate-JTDetailByNotification",
   "l": "vs live JT",
   "b": "compare/before/participate-JTDetailByNotification.png",
   "a": "compare/after/participate-JTDetailByNotification.png"
  }
 ],
 "wave1-applied-detail.html": [
  {
   "n": "participate-TutorAppliedRequestDetails",
   "l": "Approved",
   "b": "compare/before/participate-TutorAppliedRequestDetails.png",
   "a": "compare/after/participate-TutorAppliedRequestDetails.png"
  },
  {
   "n": "participate-ApplyConfirmSheet",
   "l": "Apply confirm sheet",
   "b": null,
   "a": "compare/after/participate-ApplyConfirmSheet.png"
  },
  {
   "n": "participate-TutorAppliedRequestDetails--unavailable",
   "l": "Unavailable",
   "b": "compare/before/participate-TutorAppliedRequestDetails--unavailable.png",
   "a": "compare/after/participate-TutorAppliedRequestDetails--unavailable.png"
  }
 ],
 "wave1-request-filters.html": [
  {
   "n": "participate-RequestFilters",
   "l": "Main",
   "b": "compare/before/participate-RequestFilters.png",
   "a": "compare/after/participate-RequestFilters.png"
  },
  {
   "n": "participate-SubjectPicker",
   "l": "Subject picker",
   "b": null,
   "a": "compare/after/participate-SubjectPicker.png"
  },
  {
   "n": "participate-LocationPinSheet",
   "l": "Location pin sheet",
   "b": null,
   "a": "compare/after/participate-LocationPinSheet.png"
  },
  {
   "n": "participate-RequestFilters--subject-open",
   "l": "Subject open",
   "b": "compare/before/participate-RequestFilters--subject-open.png",
   "a": "compare/after/participate-RequestFilters--subject-open.png"
  },
  {
   "n": "participate-RequestFilters--location-open",
   "l": "Location open",
   "b": "compare/before/participate-RequestFilters--location-open.png",
   "a": "compare/after/participate-RequestFilters--location-open.png"
  }
 ],
 "deliver-class-schedule.html": [
  {
   "n": "deliver-ClassSchedule",
   "l": "Main",
   "b": "compare/before/deliver-ClassSchedule.png",
   "a": "compare/after/deliver-ClassSchedule.png"
  },
  {
   "n": "deliver-ClassSchedule--day-with-class",
   "l": "Day with class",
   "b": "compare/before/deliver-ClassSchedule--day-with-class.png",
   "a": "compare/after/deliver-ClassSchedule--day-with-class.png"
  },
  {
   "n": "deliver-ClassSchedule--past-day-done",
   "l": "Past day done",
   "b": "compare/before/deliver-ClassSchedule--past-day-done.png",
   "a": "compare/after/deliver-ClassSchedule--past-day-done.png"
  },
  {
   "n": "deliver-ClassSchedule--month-expanded",
   "l": "Month expanded",
   "b": "compare/before/deliver-ClassSchedule--month-expanded.png",
   "a": "compare/after/deliver-ClassSchedule--month-expanded.png"
  },
  {
   "n": "deliver-ClassSchedule--empty-day",
   "l": "Empty day",
   "b": "compare/before/deliver-ClassSchedule--empty-day.png",
   "a": "compare/after/deliver-ClassSchedule--empty-day.png"
  }
 ],
 "deliver-add-class.html": [
  {
   "n": "deliver-AddClassSchedule",
   "l": "Main",
   "b": "compare/before/deliver-AddClassSchedule.png",
   "a": "compare/after/deliver-AddClassSchedule.png"
  },
  {
   "n": "deliver-AddClassSchedule--student-picker",
   "l": "Student picker",
   "b": "compare/before/deliver-AddClassSchedule--student-picker.png",
   "a": "compare/after/deliver-AddClassSchedule--student-picker.png"
  },
  {
   "n": "deliver-AddClassSchedule--schedule-suggestion",
   "l": "Schedule suggestion",
   "b": "compare/before/deliver-AddClassSchedule--schedule-suggestion.png",
   "a": "compare/after/deliver-AddClassSchedule--schedule-suggestion.png"
  },
  {
   "n": "deliver-AddClassSchedule--pattern-builder",
   "l": "Pattern builder",
   "b": "compare/before/deliver-AddClassSchedule--pattern-builder.png",
   "a": "compare/after/deliver-AddClassSchedule--pattern-builder.png"
  },
  {
   "n": "deliver-AddClassSchedule--manual-dates",
   "l": "Manual dates",
   "b": "compare/before/deliver-AddClassSchedule--manual-dates.png",
   "a": "compare/after/deliver-AddClassSchedule--manual-dates.png"
  },
  {
   "n": "deliver-AddClassSchedule--pattern-clash",
   "l": "Pattern clash",
   "b": "compare/before/deliver-AddClassSchedule--pattern-clash.png",
   "a": "compare/after/deliver-AddClassSchedule--pattern-clash.png"
  },
  {
   "n": "deliver-AddClassSchedule--success",
   "l": "Success",
   "b": "compare/before/deliver-AddClassSchedule--success.png",
   "a": "compare/after/deliver-AddClassSchedule--success.png"
  }
 ],
 "deliver-evaluation-report.html": [
  {
   "n": "report-EvaluationReport",
   "l": "Main",
   "b": "compare/before/report-EvaluationReport.png",
   "a": "compare/after/report-EvaluationReport.png"
  },
  {
   "n": "report-EvaluationReport--step-1",
   "l": "Step 1",
   "b": "compare/before/report-EvaluationReport--step-1.png",
   "a": "compare/after/report-EvaluationReport--step-1.png"
  },
  {
   "n": "report-EvaluationReport--step-2",
   "l": "Step 2",
   "b": "compare/before/report-EvaluationReport--step-2.png",
   "a": "compare/after/report-EvaluationReport--step-2.png"
  },
  {
   "n": "report-EvaluationReport--step-3",
   "l": "Step 3",
   "b": "compare/before/report-EvaluationReport--step-3.png",
   "a": "compare/after/report-EvaluationReport--step-3.png"
  },
  {
   "n": "report-EvaluationReport--review",
   "l": "Review",
   "b": "compare/before/report-EvaluationReport--review.png",
   "a": "compare/after/report-EvaluationReport--review.png"
  }
 ],
 "deliver-progress-report.html": [
  {
   "n": "report-ProgressReport",
   "l": "Main",
   "b": "compare/before/report-ProgressReport.png",
   "a": "compare/after/report-ProgressReport.png"
  },
  {
   "n": "report-ProgressReport--step-1-observation",
   "l": "Step 1 observation",
   "b": "compare/before/report-ProgressReport--step-1-observation.png",
   "a": "compare/after/report-ProgressReport--step-1-observation.png"
  },
  {
   "n": "report-ProgressReport--step-2-performance",
   "l": "Step 2 performance",
   "b": "compare/before/report-ProgressReport--step-2-performance.png",
   "a": "compare/after/report-ProgressReport--step-2-performance.png"
  },
  {
   "n": "report-ProgressReport--step-3-attitude",
   "l": "Step 3 attitude",
   "b": "compare/before/report-ProgressReport--step-3-attitude.png",
   "a": "compare/after/report-ProgressReport--step-3-attitude.png"
  },
  {
   "n": "report-ProgressReport--parent-summary",
   "l": "Parent summary",
   "b": "compare/before/report-ProgressReport--parent-summary.png",
   "a": "compare/after/report-ProgressReport--parent-summary.png"
  }
 ],
 "deliver-student-details.html": [
  {
   "n": "students-StudentsDetails",
   "l": "Main",
   "b": "compare/before/students-StudentsDetails.png",
   "a": "compare/after/students-StudentsDetails.png"
  },
  {
   "n": "students-StudentsDetails--online",
   "l": "Online",
   "b": "compare/before/students-StudentsDetails--online.png",
   "a": "compare/after/students-StudentsDetails--online.png"
  }
 ],
 "deliver-active-class.html": [
  {
   "n": "deliver-ActiveClass",
   "l": "Main",
   "b": "compare/before/deliver-ActiveClass.png",
   "a": "compare/after/deliver-ActiveClass.png"
  },
  {
   "n": "deliver-ActiveClassPreClass",
   "l": "Active class pre class",
   "b": null,
   "a": "compare/after/deliver-ActiveClassPreClass.png"
  },
  {
   "n": "deliver-ActiveClassClockIn",
   "l": "Active class clock in",
   "b": null,
   "a": "compare/after/deliver-ActiveClassClockIn.png"
  },
  {
   "n": "deliver-ActiveClassClockOut",
   "l": "Active class clock out",
   "b": null,
   "a": "compare/after/deliver-ActiveClassClockOut.png"
  },
  {
   "n": "deliver-ActiveClassDone",
   "l": "Active class done",
   "b": null,
   "a": "compare/after/deliver-ActiveClassDone.png"
  }
 ],
 "deliver-class-records.html": [
  {
   "n": "deliver-ClassRecords",
   "l": "Records list",
   "b": "compare/before/deliver-ClassRecords.png",
   "a": "compare/after/deliver-ClassRecords.png"
  },
  {
   "n": "deliver-ClassRecordFilter",
   "l": "Filter",
   "b": "compare/before/deliver-ClassRecordFilter.png",
   "a": "compare/after/deliver-ClassRecordFilter.png"
  },
  {
   "n": "deliver-ClassDetailByNotification",
   "l": "Class detail",
   "b": "compare/before/deliver-ClassDetailByNotification.png",
   "a": "compare/after/deliver-ClassDetailByNotification.png"
  },
  {
   "n": "deliver-ClassRecords--not-found",
   "l": "Not found",
   "b": "compare/before/deliver-ClassRecords--not-found.png",
   "a": "compare/after/deliver-ClassRecords--not-found.png"
  },
  {
   "n": "deliver-ClassRecords--filtered-empty",
   "l": "Filtered empty",
   "b": "compare/before/deliver-ClassRecords--filtered-empty.png",
   "a": "compare/after/deliver-ClassRecords--filtered-empty.png"
  }
 ],
 "deliver-class-edit.html": [
  {
   "n": "deliver-ExtraClass",
   "l": "Extend",
   "b": "compare/before/deliver-ExtraClass.png",
   "a": "compare/after/deliver-ExtraClass.png"
  },
  {
   "n": "deliver-EditPostponedClass",
   "l": "Postpone",
   "b": "compare/before/deliver-EditPostponedClass.png",
   "a": "compare/after/deliver-EditPostponedClass.png"
  },
  {
   "n": "activate-ParentApprovalConfirmation",
   "l": "Parent gate",
   "b": "compare/before/activate-ParentApprovalConfirmation.png",
   "a": "compare/after/activate-ParentApprovalConfirmation.png"
  }
 ],
 "deliver-success-variants.html": [
  {
   "n": "deliver-ClassPostponeSuccess",
   "l": "Postpone",
   "b": "compare/before/deliver-ClassPostponeSuccess.png",
   "a": "compare/after/deliver-ClassPostponeSuccess.png"
  },
  {
   "n": "deliver-ClassScheduleAdded",
   "l": "Schedule added",
   "b": "compare/before/deliver-ClassScheduleAdded.png",
   "a": "compare/after/deliver-ClassScheduleAdded.png"
  },
  {
   "n": "deliver-BackdateEscalationSuccess",
   "l": "Backdate",
   "b": "compare/before/deliver-BackdateEscalationSuccess.png",
   "a": "compare/after/deliver-BackdateEscalationSuccess.png"
  },
  {
   "n": "report-EvaluationReportSuccess",
   "l": "Evaluation",
   "b": "compare/before/report-EvaluationReportSuccess.png",
   "a": "compare/after/report-EvaluationReportSuccess.png"
  },
  {
   "n": "report-ProgressReportSuccess",
   "l": "Progress",
   "b": "compare/before/report-ProgressReportSuccess.png",
   "a": "compare/after/report-ProgressReportSuccess.png"
  }
 ],
 "deliver-student-tasks.html": [
  {
   "n": "students-StudentList",
   "l": "Students",
   "b": "compare/before/students-StudentList.png",
   "a": "compare/after/students-StudentList.png"
  },
  {
   "n": "report-StudentReport",
   "l": "Reports",
   "b": "compare/before/report-StudentReport.png",
   "a": "compare/after/report-StudentReport.png"
  },
  {
   "n": "participate-TutorTaskList",
   "l": "Tasks",
   "b": "compare/before/participate-TutorTaskList.png",
   "a": "compare/after/participate-TutorTaskList.png"
  },
  {
   "n": "deliver-StudentTasks--reports-filter",
   "l": "Reports filter",
   "b": "compare/before/deliver-StudentTasks--reports-filter.png",
   "a": "compare/after/deliver-StudentTasks--reports-filter.png"
  },
  {
   "n": "students-StudentList--empty",
   "l": "Empty",
   "b": "compare/before/students-StudentList--empty.png",
   "a": "compare/after/students-StudentList--empty.png"
  },
  {
   "n": "report-StudentReport--empty",
   "l": "Empty",
   "b": "compare/before/report-StudentReport--empty.png",
   "a": "compare/after/report-StudentReport--empty.png"
  },
  {
   "n": "participate-TutorTaskList--empty",
   "l": "Empty",
   "b": "compare/before/participate-TutorTaskList--empty.png",
   "a": "compare/after/participate-TutorTaskList--empty.png"
  }
 ],
 "deliver-camera-demand.html": [
  {
   "n": "engage-Home",
   "l": "Home demand card",
   "b": "compare/before/engage-Home.png",
   "a": "compare/after/engage-Home.png"
  },
  {
   "n": "deliver-CameraScreen",
   "l": "Camera",
   "b": null,
   "a": "compare/after/deliver-CameraScreen.png"
  }
 ],
 "profile-menu-hub.html": [
  {
   "n": "profile-ProfileMenu",
   "l": "Main",
   "b": "compare/before/profile-ProfileMenu.png",
   "a": "compare/after/profile-ProfileMenu.png"
  },
  {
   "n": "profile-ProfileMenu--new-tutor",
   "l": "New tutor",
   "b": "compare/before/profile-ProfileMenu--new-tutor.png",
   "a": "compare/after/profile-ProfileMenu--new-tutor.png"
  }
 ],
 "updateprofile-a45.html": [
  {
   "n": "activate-UpdateProfile",
   "l": "Update profile",
   "b": "compare/before/activate-UpdateProfile.png",
   "a": "compare/after/activate-UpdateProfile.png"
  },
  {
   "n": "activate-ConsentGate",
   "l": "Consent gate",
   "b": "compare/before/activate-ConsentGate.png",
   "a": "compare/after/activate-ConsentGate.png"
  },
  {
   "n": "activate-UpdateProfile--arrival",
   "l": "Arrival",
   "b": "compare/before/activate-UpdateProfile--arrival.png",
   "a": "compare/after/activate-UpdateProfile--arrival.png"
  }
 ],
 "profile-status.html": [
  {
   "n": "profile-Status",
   "l": "Main",
   "b": "compare/before/profile-Status.png",
   "a": "compare/after/profile-Status.png"
  },
  {
   "n": "profile-Status--reason-picker",
   "l": "Reason picker",
   "b": "compare/before/profile-Status--reason-picker.png",
   "a": "compare/after/profile-Status--reason-picker.png"
  }
 ],
 "profile-view.html": [
  {
   "n": "profile-Profile",
   "l": "Main",
   "b": "compare/before/profile-Profile.png",
   "a": "compare/after/profile-Profile.png"
  },
  {
   "n": "profile-Profile--complete",
   "l": "Complete",
   "b": "compare/before/profile-Profile--complete.png",
   "a": "compare/after/profile-Profile--complete.png"
  }
 ],
 "earn-payment-hub.html": [
  {
   "n": "earn-Payment",
   "l": "Earnings hub",
   "b": "compare/before/earn-Payment.png",
   "a": "compare/after/earn-Payment.png"
  },
  {
   "n": "earn-PendingEarningsDetail",
   "l": "Pending payout",
   "b": "compare/before/earn-PendingEarningsDetail.png",
   "a": "compare/after/earn-PendingEarningsDetail.png"
  },
  {
   "n": "earn-Payment--history-month",
   "l": "History month",
   "b": "compare/before/earn-Payment--history-month.png",
   "a": "compare/after/earn-Payment--history-month.png"
  },
  {
   "n": "earn-Payment--awaiting",
   "l": "Awaiting",
   "b": "compare/before/earn-Payment--awaiting.png",
   "a": "compare/after/earn-Payment--awaiting.png"
  },
  {
   "n": "earn-Payment--filter-sheet",
   "l": "Filter sheet",
   "b": "compare/before/earn-Payment--filter-sheet.png",
   "a": "compare/after/earn-Payment--filter-sheet.png"
  }
 ],
 "earn-payment-ledger.html": [
  {
   "n": "earn-PaymentLedger",
   "l": "Main",
   "b": "compare/before/earn-PaymentLedger.png",
   "a": "compare/after/earn-PaymentLedger.png"
  }
 ],
 "earn-refer.html": [
  {
   "n": "earn-ReferFriend",
   "l": "Main",
   "b": "compare/before/earn-ReferFriend.png",
   "a": "compare/after/earn-ReferFriend.png"
  },
  {
   "n": "earn-MyReferralEarnings",
   "l": "My referral earnings",
   "b": "compare/before/earn-MyReferralEarnings.png",
   "a": "compare/after/earn-MyReferralEarnings.png"
  }
 ],
 "support-ticket-picker.html": [
  {
   "n": "support-SubmitRequestPicker",
   "l": "Main",
   "b": "compare/before/support-SubmitRequestPicker.png",
   "a": "compare/after/support-SubmitRequestPicker.png"
  },
  {
   "n": "support-SubmitRequestPicker--unverified",
   "l": "Unverified",
   "b": "compare/before/support-SubmitRequestPicker--unverified.png",
   "a": "compare/after/support-SubmitRequestPicker--unverified.png"
  }
 ],
 "support-my-tickets-list.html": [
  {
   "n": "participate-MyRequestsList",
   "l": "Main",
   "b": "compare/before/participate-MyRequestsList.png",
   "a": "compare/after/participate-MyRequestsList.png"
  },
  {
   "n": "participate-MyRequestsList--empty",
   "l": "Empty",
   "b": "compare/before/participate-MyRequestsList--empty.png",
   "a": "compare/after/participate-MyRequestsList--empty.png"
  }
 ],
 "support-ticket-detail.html": [
  {
   "n": "support-TicketDetail",
   "l": "Main",
   "b": "compare/before/support-TicketDetail.png",
   "a": "compare/after/support-TicketDetail.png"
  },
  {
   "n": "support-TicketDetail--approved",
   "l": "Approved",
   "b": "compare/before/support-TicketDetail--approved.png",
   "a": "compare/after/support-TicketDetail--approved.png"
  }
 ],
 "support-application-status.html": [
  {
   "n": "support-ApplicationStatusDetail",
   "l": "Main",
   "b": "compare/before/support-ApplicationStatusDetail.png",
   "a": "compare/after/support-ApplicationStatusDetail.png"
  },
  {
   "n": "support-ApplicationStatusDetail--suspended",
   "l": "Suspended",
   "b": "compare/before/support-ApplicationStatusDetail--suspended.png",
   "a": "compare/after/support-ApplicationStatusDetail--suspended.png"
  }
 ],
 "support-form-complaint.html": [
  {
   "n": "support-SubmitRequestGeneralComplaint",
   "l": "Main",
   "b": "compare/before/support-SubmitRequestGeneralComplaint.png",
   "a": "compare/after/support-SubmitRequestGeneralComplaint.png"
  },
  {
   "n": "support-SubmitRequestGeneralComplaint--category-sheet",
   "l": "Category sheet",
   "b": "compare/before/support-SubmitRequestGeneralComplaint--category-sheet.png",
   "a": "compare/after/support-SubmitRequestGeneralComplaint--category-sheet.png"
  }
 ],
 "support-form-reschedule.html": [
  {
   "n": "support-SubmitRequestClassReschedule",
   "l": "Main",
   "b": "compare/before/support-SubmitRequestClassReschedule.png",
   "a": "compare/after/support-SubmitRequestClassReschedule.png"
  },
  {
   "n": "support-SubmitRequestClassReschedule--request-sheet",
   "l": "Request sheet",
   "b": "compare/before/support-SubmitRequestClassReschedule--request-sheet.png",
   "a": "compare/after/support-SubmitRequestClassReschedule--request-sheet.png"
  }
 ],
 "support-form-resignation.html": [
  {
   "n": "support-SubmitRequestResignation",
   "l": "Main",
   "b": "compare/before/support-SubmitRequestResignation.png",
   "a": "compare/after/support-SubmitRequestResignation.png"
  },
  {
   "n": "support-SubmitRequestResignation--confirm",
   "l": "Confirm",
   "b": "compare/before/support-SubmitRequestResignation--confirm.png",
   "a": "compare/after/support-SubmitRequestResignation--confirm.png"
  },
  {
   "n": "support-SubmitRequestResignation--guard",
   "l": "Guard",
   "b": "compare/before/support-SubmitRequestResignation--guard.png",
   "a": "compare/after/support-SubmitRequestResignation--guard.png"
  }
 ],
 "support-discouragement.html": [
  {
   "n": "support-Discouragement",
   "l": "Main",
   "b": "compare/before/support-Discouragement.png",
   "a": "compare/after/support-Discouragement.png"
  },
  {
   "n": "support-Discouragement--brand-new",
   "l": "Brand new",
   "b": "compare/before/support-Discouragement--brand-new.png",
   "a": "compare/after/support-Discouragement--brand-new.png"
  },
  {
   "n": "support-Discouragement--delete-account",
   "l": "Delete account",
   "b": "compare/before/support-Discouragement--delete-account.png",
   "a": "compare/after/support-Discouragement--delete-account.png"
  }
 ],
 "ref-news.html": [
  {
   "n": "news-News--empty",
   "l": "Empty",
   "b": "compare/before/news-News--empty.png",
   "a": "compare/after/news-News--empty.png"
  },
  {
   "n": "news-News",
   "l": "News list",
   "b": "compare/before/news-News.png",
   "a": "compare/after/news-News.png"
  },
  {
   "n": "news-NewsDetails",
   "l": "Article",
   "b": "compare/before/news-NewsDetails.png",
   "a": "compare/after/news-NewsDetails.png"
  }
 ],
 "ref-notifications.html": [
  {
   "n": "news-Notifications--empty",
   "l": "Empty",
   "b": "compare/before/news-Notifications--empty.png",
   "a": "compare/after/news-Notifications--empty.png"
  },
  {
   "n": "news-Notifications",
   "l": "Notifications",
   "b": "compare/before/news-Notifications.png",
   "a": "compare/after/news-Notifications.png"
  }
 ],
 "ref-faqs.html": [
  {
   "n": "static-FAQs--topic-expanded",
   "l": "Topic expanded",
   "b": "compare/before/static-FAQs--topic-expanded.png",
   "a": "compare/after/static-FAQs--topic-expanded.png"
  },
  {
   "n": "static-FAQs",
   "l": "FAQs",
   "b": "compare/before/static-FAQs.png",
   "a": "compare/after/static-FAQs.png"
  }
 ],
 "ref-legal.html": [
  {
   "n": "static-PrivacyPolicy",
   "l": "Privacy",
   "b": "compare/before/static-PrivacyPolicy.png",
   "a": "compare/after/static-PrivacyPolicy.png"
  },
  {
   "n": "static-TermAndConditions",
   "l": "Terms",
   "b": "compare/before/static-TermAndConditions.png",
   "a": "compare/after/static-TermAndConditions.png"
  }
 ]
};
// Per mock file: decision record (ADAPT reference board + honest headline).
window.COMPARE_DECISIONS = {
 "deliver-active-class.html": {
  "board": "refboards/teaching-now.html",
  "headline": "No whole-screen precedent exists; about half this screen is Sifututor-original."
 }
};
